### ISSUE TITLE
Can we add a place for an excel document upload for each fish entry

### ISSUE THREAD

**Issue by BDemps** [informatics-isi-edu/fishspy#10]
Currently, we create the cropbox definitions using an excel file with some formulas attached to different cells to make things quick and easy. It would be great if we could upload these excel files to each fish so that we can add to them, when necessary. For example, right now we are just making crop regions for pallium data, but eventually we also need to crop the tectum and habenula. Currently, these files are kept on individual computers or in the dropbox, and thus, it quite a bit more difficult to keep track of them.

**Comment by karlcz** [comment]
what kind of calculations?  can you give a complete example of the values you enter and the ones computed?

If it is reasonable, I'd rather add such metadata to the fish or image records (as appropriate) and we could add some formulas to the corresponding summary/dashboard view to show computed results after the raw values have already been saved in the catalog...

**Comment by BDemps** [comment]
Sure, Attached is a copy of the template we use, and one that is more filled in. I can go over it in detail, if it isn't self-explanatory
[CropBox_Template.xlsx](https://github.com/informatics-isi-edu/fishspy/files/1275432/CropBox_Template.xlsx)
[2016-06-13_A_CropBoxes.xlsx](https://github.com/informatics-isi-edu/fishspy/files/1275433/2016-06-13_A_CropBoxes.xlsx)

**Comment by karlcz** [comment]
Just started looking at this and wanted to point out that the legend on row 1 seems backwards where it talks about Z and XY voxel spacing in columns A and B, respectively...

**Comment by karlcz** [comment]
If I am understanding your spreadsheet correctly, you want a different format to specify the crop regions:
1. Continue to specify Z bounds as discrete plane indices with the same Z origin/direction synspy expects
   - Lower and upper bounds both as absolute plane numbers, upper bound exclusive
2. Specify X bounds as floating point micron distances with the same X origin/direction synspy expects
   - Absolute lower and relative upper bounds
3. Specify Y bounds as floating point micron distances with inverted Y origin/direction compared to synspy
   - Absolute lower and relative upper bounds

Is this really your most preferred format (using different units and relative vs absolute upper bounds for Z versus XY)?  If so, what leads to this odd mixture...?

If the website let you enter these preferred fields directly, would that make the spreadsheet unnecessary? Or do you have other reason you want to produce and retain this file as well?

**Comment by BDemps** [comment]
Okay, yes the combo regions would make it a lot easier just because that's how Fiji actually represents things (z in slices, XY in microns) for whatever reason, but beyond that, I'd like something that shows right away what is populated and what isn't for a given image region. Like, I'll know whether I've done all of the crops for the whole brain with a spreadsheet looking thing like this. Does this make sense at all? Maybe not...

**Comment by karlcz** [comment]
Issue moved to [informatics-isi-edu/synspy #39](https://github.com/informatics-isi-edu/synspy/issues/39) via [**ZenHub**](https://www.zenhub.com/)
