### ISSUE TITLE
Reanalysis of some older data

### ISSUE THREAD

**Issue by BDemps** [informatics-isi-edu/fishspy#11]
I was wondering whether we could maybe tweak the program for some older datasets that are going to be used for the paper. For example, BhvZfDsy20170316B1 has a LOT of red lines in the graph that are really tough to get around. Could we re-analyze it such that we can remove the red and improve the other twitch colors?

**Comment by karlcz** [comment]
I retriggered the analysis for that movie, just in case it was a stale value from before we updated the analysis code.

But, looking at that one example, it is linked to "FScope-2" which doesn't seem to have any analysis parameters defined.   You should figure out if the other old ones you don't like are in a similar state. If so, we probably need to adjust the parameters on that scope definition and then re-run them all for that scope.

**Comment by karlcz** [comment]
@BDemps  I reviewed this old issue again.  If you search the behavior data for the "FScope-2" you will see that there are at least two different flavors of movie mixed together.

Some are much brighter than others and so I think must have come from different iterations of the scope. Can you review these and reassign the appropriate FScope ID (introducing a new one if you don't think one of the existing ones is appropriate)?  The current "FScope-2" definition is only appropriate for the brighter movies where the fish is well framed so no special analysis parameters were needed.

For the scope with the darker movies, I think we need to try copying over the `FISHSPY_GAMMA` and `FISHSPY_CONTRAST` settings for `Analysis Parameters` like we have on others already.

If some of the movies are too far off from the normal framing, that would also require a different scope ID so we could set a `FISHSPY_CROP` parameter as well...

**Comment by karlcz** [comment]
@BDemps I think this issue is the same reanalysis problem we were chatting about this week. Please update here and/or close it if you think you've sorted out the different issues w/ analysis and plotting parameters...
