### ISSUE TITLE
GCaMP behavior movies - New Caddy

### ISSUE THREAD

**Issue by BDemps** [informatics-isi-edu/fishspy#12]
We may need to optimize the behavioral training analysis software to handle imaging when the fish is inside of a caddy.

I made a new protocol (PrcDsy20180226A) with an element for behavioral training movies (PrcDsy20180226A-Behave_Fscope_GCaMP), but the actual analysis fails, unfortunately (sort of expected). We have the following fish that have gone through the usual training paradigm in the new caddy that we can use to try to optimize the software (in case you want to take a look): BhvZfDsy20180214A1, BhvZfDsy20180215A1, BhvZfDsy20180215B1, BhvZfDsy20180216A1, BhvZfDsy20180216B1, BhvZfDsy20180223A1, BhvZfDsy20180223B1.

Since they are under a new protocol, would it be possible to make the debug movies appear for these types of movies always for now (we turned off debug movies for the old versions, because the code basically always seems to work in those cases)? Might be worth revisiting debug movies for now.

**Comment by BDemps** [comment]
Do you think we should crop the images more maybe?

**Comment by karlcz** [comment]
@BDemps  is this issue still relevant?

I believe we already have analysis working w/ debug movies based on the analysis parameters set for the new scope.

**Comment by BDemps** [comment]
It's definitely still relevant - I think even the new parameters aren't
great. They give an idea of twitching behavior based on the fact that the
tail now intersects with some of these regions, but the tail itself is
still pretty far from many of the points. Do you think that your
anti-vignetting approach might work?

On Mon, Mar 26, 2018 at 2:05 PM, Karl Czajkowski <notifications@github.com>
wrote:

> @BDemps
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_BDemps&d=DwMCaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=Lssj6JKak_DaRnExGYcKnQ&m=9HvaEur8jYx22-bfAEB9jowkNAUkszwrlpYoYZtWbGo&s=Xz3Sg1LGDNLTnO6neEzRr2HPAMxJ1NcNgi7D123pSDo&e=>
> is this issue still relevant?
>
> I believe we already have analysis working w/ debug movies based on the
> analysis parameters set for the new scope.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_informatics-2Disi-2Dedu_fishspy_issues_12-23issuecomment-2D376311314&d=DwMCaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=Lssj6JKak_DaRnExGYcKnQ&m=9HvaEur8jYx22-bfAEB9jowkNAUkszwrlpYoYZtWbGo&s=ZKlYyNFa0kEt3AAvhsfnq5UIgolXq491wHmKKWONmjk&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AbQSt6qIl-2DTpdiiTVo50rRLtYFMc1zNkks5tiVgEgaJpZM4SVw9s&d=DwMCaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=Lssj6JKak_DaRnExGYcKnQ&m=9HvaEur8jYx22-bfAEB9jowkNAUkszwrlpYoYZtWbGo&s=L8dnJ5niitOAmUMBLoVGWpZ_LvNPQCsCUm_JlbA3EeU&e=>
> .
>



-- 
William Dempsey, Ph.D.
Postdoctoral Scholar
Molecular and Computational Biology
Dana and David Dornsife College of Letters, Arts and Sciences
University of Southern California
wdempsey@usc.edu
Lab #: 213-821-1818

**Comment by karlcz** [comment]
I think this issue is stale and we are satisfied with the current processing
