### ISSUE TITLE
Issue with Behavioral Data Analysis

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/fishspy#6]
@BDemps commented on [Mon May 15 2017](https://github.com/informatics-isi-edu/synspy/issues/12)

(1) Zhuowei and I noticed last week that some of the behavior movies are no longer being analyzed by the data management system, specifically having to do with data from FScope 1 (20170125_FScope1). We looked into the metadata for the FScope definitions, and we think that the metadata is correct.

I'm not sure what exactly is going up, but could you potentially update this definition and perhaps re-run the images associated with it?

(2) We have noticed that the movies that we analyze with 20170315_FScope2 look qualitatively different than when we analyze the same movies on the Linux computer. I've attached two images from the same fish movie that was analyzed. "A" was done on the data management system and "B" was done on the Linux computer after moving the movie file over via dropbox.
![a_bhvzfdsy20170505b1 plot](https://cloud.githubusercontent.com/assets/28578487/26069680/a2b0a16a-3956-11e7-9d97-981733b3e9c0.png)
![b_bhvzfdsy20170505b1 plot](https://cloud.githubusercontent.com/assets/28578487/26069692/a99cb612-3956-11e7-8e04-d6a03232ada2.png)

**Comment by karlcz** [comment]
Moving this issue to the fishspy repo since it is about this software...

**Comment by karlcz** [comment]
Are you setting the `FISHSPY_INVALID_BINS` parameter when you run `fishspy-plot-results` manually?

**Comment by BDemps** [comment]
No, actually. I guess I don't remember you explaining it to me. Maybe
that's why. They are mostly qualitatively different

**Comment by karlcz** [comment]
That's strange... the effect you have in your plot with fewer red lines is what I'd expect if the invalid bins parameter was being set to mask out the bin that is showing lots of activity.

**Comment by BDemps** [comment]
Would you like me to run any again with any other parameters?

**Comment by karlcz** [comment]
No, the issue is on the server where it has been ignoring the requested contrast setting.  I'll try to get a fix for that rolled into the next server software update.

We may want to identify all the ones with qualitatively bad plots and set the server to reprocess them after the server software is updated...

**Comment by BDemps** [comment]
I see. It may be all of them that have come up after the birth date of the
FScopes, right?

**Comment by BDemps** [comment]
Something is still fishy about the FScope 2 plots. I know for a fact some of the fish last week twitched, but all of the behavior plots generated for last week basically show nothing but red lines at the tail tips. Can we make some debug movies of the plots last week to see what is going wrong?

**Comment by karlcz** [comment]
@BDemps  I've triggered a couple recent movies to be reprocessed now with the updated server software. The old plots are dropped and new ones will appear when done.  If you think these now look better, then we can dig further back and reprocess the rest of the older movies from that scope:

- BhvZfDsy20170601B1
- BhvZfDsy20170602B1

**Comment by karlcz** [comment]
It looks like the software update only improves measurement for some movies and not others. Some movies still seem to have poor SNR even after gamma and contrast adjustment.

**Comment by BDemps** [comment]
Is there a way that we can analyze all of the movies on the server and then
just make debug movies for all of them and then I'll go back and try to see
which need to be contrast improved once again or ones that are impossible
to improve?

I really don't want to lose all of these data!

On Mon, Jun 12, 2017 at 5:52 PM, Karl Czajkowski <notifications@github.com>
wrote:

> It looks like the software update only improves measurement for some
> movies and not others. Some movies still seem to have poor SNR even after
> gamma and contrast adjustment.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_informatics-2Disi-2Dedu_fishspy_issues_6-23issuecomment-2D307975354&d=DwMCaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=Lssj6JKak_DaRnExGYcKnQ&m=gA8mLMJSbGzrlMNs4lf31kbfM0rCnBdjwNTI1AhC5B8&s=zImSJGKAVEfrq0Sdg_jU0AlIwysMk1dPXwsE_jh1sbQ&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AbQSt9NAD4HETKwWUWbWEjfcZfXkggp1ks5sDd0-5FgaJpZM4Nc6pu&d=DwMCaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=Lssj6JKak_DaRnExGYcKnQ&m=gA8mLMJSbGzrlMNs4lf31kbfM0rCnBdjwNTI1AhC5B8&s=w2_XfKOyqJP2l1tTfNU3dcvOhHGGXKLQSzWCypYNBFc&e=>
> .
>



-- 
William Dempsey, Ph.D.
Postdoctoral Scholar
Molecular and Computational Biology
Dana and David Dornsife College of Letters, Arts and Sciences
University of Southern California
wdempsey@usc.edu
Lab #: 213-821-1818

**Comment by karlcz** [comment]
There was a separate data-management bug that caused revised plots to be discarded and the previous plot results to be restored.  This is corrected and all affected plots have been regenerated again.  A second pass is now adding debug movies for all data on that scope.
